#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CongTyXayDung")]
	public partial class CTYXAYDUNGDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCongTrinh(CongTrinh instance);
    partial void UpdateCongTrinh(CongTrinh instance);
    partial void DeleteCongTrinh(CongTrinh instance);
    partial void InsertCongTrinh_NhaThau(CongTrinh_NhaThau instance);
    partial void UpdateCongTrinh_NhaThau(CongTrinh_NhaThau instance);
    partial void DeleteCongTrinh_NhaThau(CongTrinh_NhaThau instance);
    partial void InsertCongTrinh_VatTu(CongTrinh_VatTu instance);
    partial void UpdateCongTrinh_VatTu(CongTrinh_VatTu instance);
    partial void DeleteCongTrinh_VatTu(CongTrinh_VatTu instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNhanCong(NhanCong instance);
    partial void UpdateNhanCong(NhanCong instance);
    partial void DeleteNhanCong(NhanCong instance);
    partial void InsertNhaThau(NhaThau instance);
    partial void UpdateNhaThau(NhaThau instance);
    partial void DeleteNhaThau(NhaThau instance);
    partial void InsertPhanCong(PhanCong instance);
    partial void UpdatePhanCong(PhanCong instance);
    partial void DeletePhanCong(PhanCong instance);
    partial void InsertTienDo(TienDo instance);
    partial void UpdateTienDo(TienDo instance);
    partial void DeleteTienDo(TienDo instance);
    partial void InsertVatTu(VatTu instance);
    partial void UpdateVatTu(VatTu instance);
    partial void DeleteVatTu(VatTu instance);
    #endregion
		
		public CTYXAYDUNGDataContext() : 
				base(global::DAL.Properties.Settings.Default.CongTyXayDungConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public CTYXAYDUNGDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CTYXAYDUNGDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CTYXAYDUNGDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CTYXAYDUNGDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CongTrinh> CongTrinhs
		{
			get
			{
				return this.GetTable<CongTrinh>();
			}
		}
		
		public System.Data.Linq.Table<CongTrinh_NhaThau> CongTrinh_NhaThaus
		{
			get
			{
				return this.GetTable<CongTrinh_NhaThau>();
			}
		}
		
		public System.Data.Linq.Table<CongTrinh_VatTu> CongTrinh_VatTus
		{
			get
			{
				return this.GetTable<CongTrinh_VatTu>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NhanCong> NhanCongs
		{
			get
			{
				return this.GetTable<NhanCong>();
			}
		}
		
		public System.Data.Linq.Table<NhaThau> NhaThaus
		{
			get
			{
				return this.GetTable<NhaThau>();
			}
		}
		
		public System.Data.Linq.Table<PhanCong> PhanCongs
		{
			get
			{
				return this.GetTable<PhanCong>();
			}
		}
		
		public System.Data.Linq.Table<TienDo> TienDos
		{
			get
			{
				return this.GetTable<TienDo>();
			}
		}
		
		public System.Data.Linq.Table<VatTu> VatTus
		{
			get
			{
				return this.GetTable<VatTu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTrinh")]
	public partial class CongTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _dia_diem;
		
		private string _chu_dau_tu;
		
		private System.Nullable<System.DateTime> _ngay_bat_dau;
		
		private System.Nullable<System.DateTime> _ngay_du_kien_ket_thuc;
		
		private System.Nullable<System.DateTime> _ngay_hoan_thanh;
		
		private string _trang_thai;
		
		private System.Nullable<decimal> _tong_muc_dau_tu;
		
		private string _hinh_anh;
		
		private EntitySet<CongTrinh_NhaThau> _CongTrinh_NhaThaus;
		
		private EntitySet<CongTrinh_VatTu> _CongTrinh_VatTus;
		
		private EntitySet<PhanCong> _PhanCongs;
		
		private EntitySet<TienDo> _TienDos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Ondia_diemChanging(string value);
    partial void Ondia_diemChanged();
    partial void Onchu_dau_tuChanging(string value);
    partial void Onchu_dau_tuChanged();
    partial void Onngay_bat_dauChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_bat_dauChanged();
    partial void Onngay_du_kien_ket_thucChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_du_kien_ket_thucChanged();
    partial void Onngay_hoan_thanhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_hoan_thanhChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Ontong_muc_dau_tuChanging(System.Nullable<decimal> value);
    partial void Ontong_muc_dau_tuChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    #endregion
		
		public CongTrinh()
		{
			this._CongTrinh_NhaThaus = new EntitySet<CongTrinh_NhaThau>(new Action<CongTrinh_NhaThau>(this.attach_CongTrinh_NhaThaus), new Action<CongTrinh_NhaThau>(this.detach_CongTrinh_NhaThaus));
			this._CongTrinh_VatTus = new EntitySet<CongTrinh_VatTu>(new Action<CongTrinh_VatTu>(this.attach_CongTrinh_VatTus), new Action<CongTrinh_VatTu>(this.detach_CongTrinh_VatTus));
			this._PhanCongs = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs), new Action<PhanCong>(this.detach_PhanCongs));
			this._TienDos = new EntitySet<TienDo>(new Action<TienDo>(this.attach_TienDos), new Action<TienDo>(this.detach_TienDos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_diem", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string dia_diem
		{
			get
			{
				return this._dia_diem;
			}
			set
			{
				if ((this._dia_diem != value))
				{
					this.Ondia_diemChanging(value);
					this.SendPropertyChanging();
					this._dia_diem = value;
					this.SendPropertyChanged("dia_diem");
					this.Ondia_diemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chu_dau_tu", DbType="NVarChar(100)")]
		public string chu_dau_tu
		{
			get
			{
				return this._chu_dau_tu;
			}
			set
			{
				if ((this._chu_dau_tu != value))
				{
					this.Onchu_dau_tuChanging(value);
					this.SendPropertyChanging();
					this._chu_dau_tu = value;
					this.SendPropertyChanged("chu_dau_tu");
					this.Onchu_dau_tuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_bat_dau", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_bat_dau
		{
			get
			{
				return this._ngay_bat_dau;
			}
			set
			{
				if ((this._ngay_bat_dau != value))
				{
					this.Onngay_bat_dauChanging(value);
					this.SendPropertyChanging();
					this._ngay_bat_dau = value;
					this.SendPropertyChanged("ngay_bat_dau");
					this.Onngay_bat_dauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_du_kien_ket_thuc", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_du_kien_ket_thuc
		{
			get
			{
				return this._ngay_du_kien_ket_thuc;
			}
			set
			{
				if ((this._ngay_du_kien_ket_thuc != value))
				{
					this.Onngay_du_kien_ket_thucChanging(value);
					this.SendPropertyChanging();
					this._ngay_du_kien_ket_thuc = value;
					this.SendPropertyChanged("ngay_du_kien_ket_thuc");
					this.Onngay_du_kien_ket_thucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_hoan_thanh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_hoan_thanh
		{
			get
			{
				return this._ngay_hoan_thanh;
			}
			set
			{
				if ((this._ngay_hoan_thanh != value))
				{
					this.Onngay_hoan_thanhChanging(value);
					this.SendPropertyChanging();
					this._ngay_hoan_thanh = value;
					this.SendPropertyChanged("ngay_hoan_thanh");
					this.Onngay_hoan_thanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(20)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_muc_dau_tu", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> tong_muc_dau_tu
		{
			get
			{
				return this._tong_muc_dau_tu;
			}
			set
			{
				if ((this._tong_muc_dau_tu != value))
				{
					this.Ontong_muc_dau_tuChanging(value);
					this.SendPropertyChanging();
					this._tong_muc_dau_tu = value;
					this.SendPropertyChanged("tong_muc_dau_tu");
					this.Ontong_muc_dau_tuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="NVarChar(255)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_CongTrinh_NhaThau", Storage="_CongTrinh_NhaThaus", ThisKey="id", OtherKey="cong_trinh_id")]
		public EntitySet<CongTrinh_NhaThau> CongTrinh_NhaThaus
		{
			get
			{
				return this._CongTrinh_NhaThaus;
			}
			set
			{
				this._CongTrinh_NhaThaus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_CongTrinh_VatTu", Storage="_CongTrinh_VatTus", ThisKey="id", OtherKey="cong_trinh_id")]
		public EntitySet<CongTrinh_VatTu> CongTrinh_VatTus
		{
			get
			{
				return this._CongTrinh_VatTus;
			}
			set
			{
				this._CongTrinh_VatTus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_PhanCong", Storage="_PhanCongs", ThisKey="id", OtherKey="cong_trinh_id")]
		public EntitySet<PhanCong> PhanCongs
		{
			get
			{
				return this._PhanCongs;
			}
			set
			{
				this._PhanCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_TienDo", Storage="_TienDos", ThisKey="id", OtherKey="cong_trinh_id")]
		public EntitySet<TienDo> TienDos
		{
			get
			{
				return this._TienDos;
			}
			set
			{
				this._TienDos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongTrinh_NhaThaus(CongTrinh_NhaThau entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = this;
		}
		
		private void detach_CongTrinh_NhaThaus(CongTrinh_NhaThau entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = null;
		}
		
		private void attach_CongTrinh_VatTus(CongTrinh_VatTu entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = this;
		}
		
		private void detach_CongTrinh_VatTus(CongTrinh_VatTu entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = null;
		}
		
		private void attach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = this;
		}
		
		private void detach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = null;
		}
		
		private void attach_TienDos(TienDo entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = this;
		}
		
		private void detach_TienDos(TienDo entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTrinh_NhaThau")]
	public partial class CongTrinh_NhaThau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cong_trinh_id;
		
		private int _nha_thau_id;
		
		private string _vai_tro;
		
		private EntityRef<CongTrinh> _CongTrinh;
		
		private EntityRef<NhaThau> _NhaThau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncong_trinh_idChanging(int value);
    partial void Oncong_trinh_idChanged();
    partial void Onnha_thau_idChanging(int value);
    partial void Onnha_thau_idChanged();
    partial void Onvai_troChanging(string value);
    partial void Onvai_troChanged();
    #endregion
		
		public CongTrinh_NhaThau()
		{
			this._CongTrinh = default(EntityRef<CongTrinh>);
			this._NhaThau = default(EntityRef<NhaThau>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cong_trinh_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cong_trinh_id
		{
			get
			{
				return this._cong_trinh_id;
			}
			set
			{
				if ((this._cong_trinh_id != value))
				{
					if (this._CongTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncong_trinh_idChanging(value);
					this.SendPropertyChanging();
					this._cong_trinh_id = value;
					this.SendPropertyChanged("cong_trinh_id");
					this.Oncong_trinh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nha_thau_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nha_thau_id
		{
			get
			{
				return this._nha_thau_id;
			}
			set
			{
				if ((this._nha_thau_id != value))
				{
					if (this._NhaThau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnha_thau_idChanging(value);
					this.SendPropertyChanging();
					this._nha_thau_id = value;
					this.SendPropertyChanged("nha_thau_id");
					this.Onnha_thau_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vai_tro", DbType="NVarChar(50)")]
		public string vai_tro
		{
			get
			{
				return this._vai_tro;
			}
			set
			{
				if ((this._vai_tro != value))
				{
					this.Onvai_troChanging(value);
					this.SendPropertyChanging();
					this._vai_tro = value;
					this.SendPropertyChanged("vai_tro");
					this.Onvai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_CongTrinh_NhaThau", Storage="_CongTrinh", ThisKey="cong_trinh_id", OtherKey="id", IsForeignKey=true)]
		public CongTrinh CongTrinh
		{
			get
			{
				return this._CongTrinh.Entity;
			}
			set
			{
				CongTrinh previousValue = this._CongTrinh.Entity;
				if (((previousValue != value) 
							|| (this._CongTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTrinh.Entity = null;
						previousValue.CongTrinh_NhaThaus.Remove(this);
					}
					this._CongTrinh.Entity = value;
					if ((value != null))
					{
						value.CongTrinh_NhaThaus.Add(this);
						this._cong_trinh_id = value.id;
					}
					else
					{
						this._cong_trinh_id = default(int);
					}
					this.SendPropertyChanged("CongTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaThau_CongTrinh_NhaThau", Storage="_NhaThau", ThisKey="nha_thau_id", OtherKey="id", IsForeignKey=true)]
		public NhaThau NhaThau
		{
			get
			{
				return this._NhaThau.Entity;
			}
			set
			{
				NhaThau previousValue = this._NhaThau.Entity;
				if (((previousValue != value) 
							|| (this._NhaThau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaThau.Entity = null;
						previousValue.CongTrinh_NhaThaus.Remove(this);
					}
					this._NhaThau.Entity = value;
					if ((value != null))
					{
						value.CongTrinh_NhaThaus.Add(this);
						this._nha_thau_id = value.id;
					}
					else
					{
						this._nha_thau_id = default(int);
					}
					this.SendPropertyChanged("NhaThau");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTrinh_VatTu")]
	public partial class CongTrinh_VatTu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cong_trinh_id;
		
		private int _vat_tu_id;
		
		private System.Nullable<decimal> _so_luong;
		
		private System.Nullable<decimal> _don_gia;
		
		private System.DateTime _ngay_su_dung;
		
		private EntityRef<CongTrinh> _CongTrinh;
		
		private EntityRef<VatTu> _VatTu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncong_trinh_idChanging(int value);
    partial void Oncong_trinh_idChanged();
    partial void Onvat_tu_idChanging(int value);
    partial void Onvat_tu_idChanged();
    partial void Onso_luongChanging(System.Nullable<decimal> value);
    partial void Onso_luongChanged();
    partial void Ondon_giaChanging(System.Nullable<decimal> value);
    partial void Ondon_giaChanged();
    partial void Onngay_su_dungChanging(System.DateTime value);
    partial void Onngay_su_dungChanged();
    #endregion
		
		public CongTrinh_VatTu()
		{
			this._CongTrinh = default(EntityRef<CongTrinh>);
			this._VatTu = default(EntityRef<VatTu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cong_trinh_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cong_trinh_id
		{
			get
			{
				return this._cong_trinh_id;
			}
			set
			{
				if ((this._cong_trinh_id != value))
				{
					if (this._CongTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncong_trinh_idChanging(value);
					this.SendPropertyChanging();
					this._cong_trinh_id = value;
					this.SendPropertyChanged("cong_trinh_id");
					this.Oncong_trinh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vat_tu_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int vat_tu_id
		{
			get
			{
				return this._vat_tu_id;
			}
			set
			{
				if ((this._vat_tu_id != value))
				{
					if (this._VatTu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onvat_tu_idChanging(value);
					this.SendPropertyChanging();
					this._vat_tu_id = value;
					this.SendPropertyChanged("vat_tu_id");
					this.Onvat_tu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_gia", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> don_gia
		{
			get
			{
				return this._don_gia;
			}
			set
			{
				if ((this._don_gia != value))
				{
					this.Ondon_giaChanging(value);
					this.SendPropertyChanging();
					this._don_gia = value;
					this.SendPropertyChanged("don_gia");
					this.Ondon_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_su_dung", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ngay_su_dung
		{
			get
			{
				return this._ngay_su_dung;
			}
			set
			{
				if ((this._ngay_su_dung != value))
				{
					this.Onngay_su_dungChanging(value);
					this.SendPropertyChanging();
					this._ngay_su_dung = value;
					this.SendPropertyChanged("ngay_su_dung");
					this.Onngay_su_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_CongTrinh_VatTu", Storage="_CongTrinh", ThisKey="cong_trinh_id", OtherKey="id", IsForeignKey=true)]
		public CongTrinh CongTrinh
		{
			get
			{
				return this._CongTrinh.Entity;
			}
			set
			{
				CongTrinh previousValue = this._CongTrinh.Entity;
				if (((previousValue != value) 
							|| (this._CongTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTrinh.Entity = null;
						previousValue.CongTrinh_VatTus.Remove(this);
					}
					this._CongTrinh.Entity = value;
					if ((value != null))
					{
						value.CongTrinh_VatTus.Add(this);
						this._cong_trinh_id = value.id;
					}
					else
					{
						this._cong_trinh_id = default(int);
					}
					this.SendPropertyChanged("CongTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VatTu_CongTrinh_VatTu", Storage="_VatTu", ThisKey="vat_tu_id", OtherKey="id", IsForeignKey=true)]
		public VatTu VatTu
		{
			get
			{
				return this._VatTu.Entity;
			}
			set
			{
				VatTu previousValue = this._VatTu.Entity;
				if (((previousValue != value) 
							|| (this._VatTu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VatTu.Entity = null;
						previousValue.CongTrinh_VatTus.Remove(this);
					}
					this._VatTu.Entity = value;
					if ((value != null))
					{
						value.CongTrinh_VatTus.Add(this);
						this._vat_tu_id = value.id;
					}
					else
					{
						this._vat_tu_id = default(int);
					}
					this.SendPropertyChanged("VatTu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten_dang_nhap;
		
		private string _mat_khau;
		
		private string _ho_ten;
		
		private string _so_dien_thoai;
		
		private string _email;
		
		private string _vai_tro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onten_dang_nhapChanging(string value);
    partial void Onten_dang_nhapChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onvai_troChanging(string value);
    partial void Onvai_troChanged();
    #endregion
		
		public NguoiDung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dang_nhap", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_dang_nhap
		{
			get
			{
				return this._ten_dang_nhap;
			}
			set
			{
				if ((this._ten_dang_nhap != value))
				{
					this.Onten_dang_nhapChanging(value);
					this.SendPropertyChanging();
					this._ten_dang_nhap = value;
					this.SendPropertyChanged("ten_dang_nhap");
					this.Onten_dang_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(100)")]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="VarChar(15)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vai_tro", DbType="NVarChar(10)")]
		public string vai_tro
		{
			get
			{
				return this._vai_tro;
			}
			set
			{
				if ((this._vai_tro != value))
				{
					this.Onvai_troChanging(value);
					this.SendPropertyChanging();
					this._vai_tro = value;
					this.SendPropertyChanged("vai_tro");
					this.Onvai_troChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanCong")]
	public partial class NhanCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ho_ten;
		
		private string _chuc_vu;
		
		private System.Nullable<decimal> _luong_ngay;
		
		private string _so_dien_thoai;
		
		private EntitySet<PhanCong> _PhanCongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Onchuc_vuChanging(string value);
    partial void Onchuc_vuChanged();
    partial void Onluong_ngayChanging(System.Nullable<decimal> value);
    partial void Onluong_ngayChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    #endregion
		
		public NhanCong()
		{
			this._PhanCongs = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs), new Action<PhanCong>(this.detach_PhanCongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuc_vu", DbType="NVarChar(50)")]
		public string chuc_vu
		{
			get
			{
				return this._chuc_vu;
			}
			set
			{
				if ((this._chuc_vu != value))
				{
					this.Onchuc_vuChanging(value);
					this.SendPropertyChanging();
					this._chuc_vu = value;
					this.SendPropertyChanged("chuc_vu");
					this.Onchuc_vuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong_ngay", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> luong_ngay
		{
			get
			{
				return this._luong_ngay;
			}
			set
			{
				if ((this._luong_ngay != value))
				{
					this.Onluong_ngayChanging(value);
					this.SendPropertyChanging();
					this._luong_ngay = value;
					this.SendPropertyChanged("luong_ngay");
					this.Onluong_ngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="VarChar(15)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanCong_PhanCong", Storage="_PhanCongs", ThisKey="id", OtherKey="nhan_cong_id")]
		public EntitySet<PhanCong> PhanCongs
		{
			get
			{
				return this._PhanCongs;
			}
			set
			{
				this._PhanCongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.NhanCong = this;
		}
		
		private void detach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.NhanCong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaThau")]
	public partial class NhaThau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten_cong_ty;
		
		private string _ma_so_thue;
		
		private string _dia_chi;
		
		private string _nguoi_dai_dien;
		
		private string _so_dien_thoai;
		
		private string _email;
		
		private EntitySet<CongTrinh_NhaThau> _CongTrinh_NhaThaus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onten_cong_tyChanging(string value);
    partial void Onten_cong_tyChanged();
    partial void Onma_so_thueChanging(string value);
    partial void Onma_so_thueChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Onnguoi_dai_dienChanging(string value);
    partial void Onnguoi_dai_dienChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public NhaThau()
		{
			this._CongTrinh_NhaThaus = new EntitySet<CongTrinh_NhaThau>(new Action<CongTrinh_NhaThau>(this.attach_CongTrinh_NhaThaus), new Action<CongTrinh_NhaThau>(this.detach_CongTrinh_NhaThaus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_cong_ty", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_cong_ty
		{
			get
			{
				return this._ten_cong_ty;
			}
			set
			{
				if ((this._ten_cong_ty != value))
				{
					this.Onten_cong_tyChanging(value);
					this.SendPropertyChanging();
					this._ten_cong_ty = value;
					this.SendPropertyChanged("ten_cong_ty");
					this.Onten_cong_tyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_so_thue", DbType="VarChar(20)")]
		public string ma_so_thue
		{
			get
			{
				return this._ma_so_thue;
			}
			set
			{
				if ((this._ma_so_thue != value))
				{
					this.Onma_so_thueChanging(value);
					this.SendPropertyChanging();
					this._ma_so_thue = value;
					this.SendPropertyChanged("ma_so_thue");
					this.Onma_so_thueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(200)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dai_dien", DbType="NVarChar(50)")]
		public string nguoi_dai_dien
		{
			get
			{
				return this._nguoi_dai_dien;
			}
			set
			{
				if ((this._nguoi_dai_dien != value))
				{
					this.Onnguoi_dai_dienChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dai_dien = value;
					this.SendPropertyChanged("nguoi_dai_dien");
					this.Onnguoi_dai_dienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="VarChar(15)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaThau_CongTrinh_NhaThau", Storage="_CongTrinh_NhaThaus", ThisKey="id", OtherKey="nha_thau_id")]
		public EntitySet<CongTrinh_NhaThau> CongTrinh_NhaThaus
		{
			get
			{
				return this._CongTrinh_NhaThaus;
			}
			set
			{
				this._CongTrinh_NhaThaus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongTrinh_NhaThaus(CongTrinh_NhaThau entity)
		{
			this.SendPropertyChanging();
			entity.NhaThau = this;
		}
		
		private void detach_CongTrinh_NhaThaus(CongTrinh_NhaThau entity)
		{
			this.SendPropertyChanging();
			entity.NhaThau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanCong")]
	public partial class PhanCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cong_trinh_id;
		
		private int _nhan_cong_id;
		
		private System.DateTime _ngay_bat_dau;
		
		private System.Nullable<System.DateTime> _ngay_ket_thuc;
		
		private EntityRef<CongTrinh> _CongTrinh;
		
		private EntityRef<NhanCong> _NhanCong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncong_trinh_idChanging(int value);
    partial void Oncong_trinh_idChanged();
    partial void Onnhan_cong_idChanging(int value);
    partial void Onnhan_cong_idChanged();
    partial void Onngay_bat_dauChanging(System.DateTime value);
    partial void Onngay_bat_dauChanged();
    partial void Onngay_ket_thucChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_ket_thucChanged();
    #endregion
		
		public PhanCong()
		{
			this._CongTrinh = default(EntityRef<CongTrinh>);
			this._NhanCong = default(EntityRef<NhanCong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cong_trinh_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cong_trinh_id
		{
			get
			{
				return this._cong_trinh_id;
			}
			set
			{
				if ((this._cong_trinh_id != value))
				{
					if (this._CongTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncong_trinh_idChanging(value);
					this.SendPropertyChanging();
					this._cong_trinh_id = value;
					this.SendPropertyChanged("cong_trinh_id");
					this.Oncong_trinh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhan_cong_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nhan_cong_id
		{
			get
			{
				return this._nhan_cong_id;
			}
			set
			{
				if ((this._nhan_cong_id != value))
				{
					if (this._NhanCong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnhan_cong_idChanging(value);
					this.SendPropertyChanging();
					this._nhan_cong_id = value;
					this.SendPropertyChanged("nhan_cong_id");
					this.Onnhan_cong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_bat_dau", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ngay_bat_dau
		{
			get
			{
				return this._ngay_bat_dau;
			}
			set
			{
				if ((this._ngay_bat_dau != value))
				{
					this.Onngay_bat_dauChanging(value);
					this.SendPropertyChanging();
					this._ngay_bat_dau = value;
					this.SendPropertyChanged("ngay_bat_dau");
					this.Onngay_bat_dauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_ket_thuc", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_ket_thuc
		{
			get
			{
				return this._ngay_ket_thuc;
			}
			set
			{
				if ((this._ngay_ket_thuc != value))
				{
					this.Onngay_ket_thucChanging(value);
					this.SendPropertyChanging();
					this._ngay_ket_thuc = value;
					this.SendPropertyChanged("ngay_ket_thuc");
					this.Onngay_ket_thucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_PhanCong", Storage="_CongTrinh", ThisKey="cong_trinh_id", OtherKey="id", IsForeignKey=true)]
		public CongTrinh CongTrinh
		{
			get
			{
				return this._CongTrinh.Entity;
			}
			set
			{
				CongTrinh previousValue = this._CongTrinh.Entity;
				if (((previousValue != value) 
							|| (this._CongTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTrinh.Entity = null;
						previousValue.PhanCongs.Remove(this);
					}
					this._CongTrinh.Entity = value;
					if ((value != null))
					{
						value.PhanCongs.Add(this);
						this._cong_trinh_id = value.id;
					}
					else
					{
						this._cong_trinh_id = default(int);
					}
					this.SendPropertyChanged("CongTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanCong_PhanCong", Storage="_NhanCong", ThisKey="nhan_cong_id", OtherKey="id", IsForeignKey=true)]
		public NhanCong NhanCong
		{
			get
			{
				return this._NhanCong.Entity;
			}
			set
			{
				NhanCong previousValue = this._NhanCong.Entity;
				if (((previousValue != value) 
							|| (this._NhanCong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanCong.Entity = null;
						previousValue.PhanCongs.Remove(this);
					}
					this._NhanCong.Entity = value;
					if ((value != null))
					{
						value.PhanCongs.Add(this);
						this._nhan_cong_id = value.id;
					}
					else
					{
						this._nhan_cong_id = default(int);
					}
					this.SendPropertyChanged("NhanCong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TienDo")]
	public partial class TienDo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _cong_trinh_id;
		
		private System.Nullable<System.DateTime> _ngay_cap_nhat;
		
		private string _mo_ta;
		
		private System.Nullable<decimal> _phan_tram_hoan_thanh;
		
		private EntityRef<CongTrinh> _CongTrinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncong_trinh_idChanging(System.Nullable<int> value);
    partial void Oncong_trinh_idChanged();
    partial void Onngay_cap_nhatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_nhatChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Onphan_tram_hoan_thanhChanging(System.Nullable<decimal> value);
    partial void Onphan_tram_hoan_thanhChanged();
    #endregion
		
		public TienDo()
		{
			this._CongTrinh = default(EntityRef<CongTrinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cong_trinh_id", DbType="Int")]
		public System.Nullable<int> cong_trinh_id
		{
			get
			{
				return this._cong_trinh_id;
			}
			set
			{
				if ((this._cong_trinh_id != value))
				{
					if (this._CongTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncong_trinh_idChanging(value);
					this.SendPropertyChanging();
					this._cong_trinh_id = value;
					this.SendPropertyChanged("cong_trinh_id");
					this.Oncong_trinh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(MAX)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phan_tram_hoan_thanh", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> phan_tram_hoan_thanh
		{
			get
			{
				return this._phan_tram_hoan_thanh;
			}
			set
			{
				if ((this._phan_tram_hoan_thanh != value))
				{
					this.Onphan_tram_hoan_thanhChanging(value);
					this.SendPropertyChanging();
					this._phan_tram_hoan_thanh = value;
					this.SendPropertyChanged("phan_tram_hoan_thanh");
					this.Onphan_tram_hoan_thanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_TienDo", Storage="_CongTrinh", ThisKey="cong_trinh_id", OtherKey="id", IsForeignKey=true)]
		public CongTrinh CongTrinh
		{
			get
			{
				return this._CongTrinh.Entity;
			}
			set
			{
				CongTrinh previousValue = this._CongTrinh.Entity;
				if (((previousValue != value) 
							|| (this._CongTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTrinh.Entity = null;
						previousValue.TienDos.Remove(this);
					}
					this._CongTrinh.Entity = value;
					if ((value != null))
					{
						value.TienDos.Add(this);
						this._cong_trinh_id = value.id;
					}
					else
					{
						this._cong_trinh_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("CongTrinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VatTu")]
	public partial class VatTu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ma_vat_tu;
		
		private string _ten;
		
		private string _don_vi_tinh;
		
		private System.Nullable<decimal> _don_gia;
		
		private string _nha_cung_cap;
		
		private string _hinh_anh;
		
		private EntitySet<CongTrinh_VatTu> _CongTrinh_VatTus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onma_vat_tuChanging(string value);
    partial void Onma_vat_tuChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Ondon_vi_tinhChanging(string value);
    partial void Ondon_vi_tinhChanged();
    partial void Ondon_giaChanging(System.Nullable<decimal> value);
    partial void Ondon_giaChanged();
    partial void Onnha_cung_capChanging(string value);
    partial void Onnha_cung_capChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    #endregion
		
		public VatTu()
		{
			this._CongTrinh_VatTus = new EntitySet<CongTrinh_VatTu>(new Action<CongTrinh_VatTu>(this.attach_CongTrinh_VatTus), new Action<CongTrinh_VatTu>(this.detach_CongTrinh_VatTus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_vat_tu", DbType="VarChar(20)")]
		public string ma_vat_tu
		{
			get
			{
				return this._ma_vat_tu;
			}
			set
			{
				if ((this._ma_vat_tu != value))
				{
					this.Onma_vat_tuChanging(value);
					this.SendPropertyChanging();
					this._ma_vat_tu = value;
					this.SendPropertyChanged("ma_vat_tu");
					this.Onma_vat_tuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_vi_tinh", DbType="NVarChar(20)")]
		public string don_vi_tinh
		{
			get
			{
				return this._don_vi_tinh;
			}
			set
			{
				if ((this._don_vi_tinh != value))
				{
					this.Ondon_vi_tinhChanging(value);
					this.SendPropertyChanging();
					this._don_vi_tinh = value;
					this.SendPropertyChanged("don_vi_tinh");
					this.Ondon_vi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_gia", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> don_gia
		{
			get
			{
				return this._don_gia;
			}
			set
			{
				if ((this._don_gia != value))
				{
					this.Ondon_giaChanging(value);
					this.SendPropertyChanging();
					this._don_gia = value;
					this.SendPropertyChanged("don_gia");
					this.Ondon_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nha_cung_cap", DbType="NVarChar(100)")]
		public string nha_cung_cap
		{
			get
			{
				return this._nha_cung_cap;
			}
			set
			{
				if ((this._nha_cung_cap != value))
				{
					this.Onnha_cung_capChanging(value);
					this.SendPropertyChanging();
					this._nha_cung_cap = value;
					this.SendPropertyChanged("nha_cung_cap");
					this.Onnha_cung_capChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="NVarChar(255)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VatTu_CongTrinh_VatTu", Storage="_CongTrinh_VatTus", ThisKey="id", OtherKey="vat_tu_id")]
		public EntitySet<CongTrinh_VatTu> CongTrinh_VatTus
		{
			get
			{
				return this._CongTrinh_VatTus;
			}
			set
			{
				this._CongTrinh_VatTus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongTrinh_VatTus(CongTrinh_VatTu entity)
		{
			this.SendPropertyChanging();
			entity.VatTu = this;
		}
		
		private void detach_CongTrinh_VatTus(CongTrinh_VatTu entity)
		{
			this.SendPropertyChanging();
			entity.VatTu = null;
		}
	}
}
#pragma warning restore 1591
